# CVB강의6-고전컴퓨터비전-심화예제실습

**목차**
1. GitHub 저장소를 이용해 이미지 Import 실습   
  1.1 GitHub 저장소에서 이미지 불러오기   
2. OpenCV Library를 이용한 Canny Edge Detection 실습   
  2.1 OpenCV Library를 활용하여 Canny Edge Detector 구현 및 입출력 비교하기   
3. OpenCV Library를 이용한 Contour Detection 실습   
  3.1 OpenCV Library를 활용하여 Contour Detection 구현 및 입출력 비교하기    
  3.2 Dilation Kernel을 활용하여 Contour Detection 성능 개선하기

## 0. 환경설정


```python
!pip3 install opencv-python==4.8.0.76
!pip3 install numpy==1.23.5
!pip3 install matplotlib==3.7.1
```

    Requirement already satisfied: opencv-python==4.8.0.76 in /usr/local/lib/python3.10/dist-packages (4.8.0.76)
    Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.10/dist-packages (from opencv-python==4.8.0.76) (1.25.2)
    Collecting numpy==1.23.5
      Downloading numpy-1.23.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
    [2K     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m17.1/17.1 MB[0m [31m20.7 MB/s[0m eta [36m0:00:00[0m
    [?25hInstalling collected packages: numpy
      Attempting uninstall: numpy
        Found existing installation: numpy 1.25.2
        Uninstalling numpy-1.25.2:
          Successfully uninstalled numpy-1.25.2
    [31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
    chex 0.1.86 requires numpy>=1.24.1, but you have numpy 1.23.5 which is incompatible.
    pandas-stubs 2.0.3.230814 requires numpy>=1.25.0; python_version >= "3.9", but you have numpy 1.23.5 which is incompatible.[0m[31m
    [0mSuccessfully installed numpy-1.23.5
    



    Requirement already satisfied: matplotlib==3.7.1 in /usr/local/lib/python3.10/dist-packages (3.7.1)
    Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1) (1.2.1)
    Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1) (0.12.1)
    Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1) (4.53.1)
    Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1) (1.4.5)
    Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1) (1.23.5)
    Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1) (24.1)
    Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1) (9.4.0)
    Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1) (3.1.2)
    Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib==3.7.1) (2.8.2)
    Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib==3.7.1) (1.16.0)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3108, in _dep_map
        return self.__dep_map
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2901, in __getattr__
        raise AttributeError(attr)
    AttributeError: _DistInfoDistribution__dep_map
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
        status = run_func(*args)
      File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/req_command.py", line 242, in wrapper
        return func(self, options, args)
      File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py", line 441, in run
        conflicts = self._determine_conflicts(to_install)
      File "/usr/local/lib/python3.10/dist-packages/pip/_internal/commands/install.py", line 572, in _determine_conflicts
        return check_install_conflicts(to_install)
      File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/check.py", line 101, in check_install_conflicts
        package_set, _ = create_package_set_from_installed()
      File "/usr/local/lib/python3.10/dist-packages/pip/_internal/operations/check.py", line 42, in create_package_set_from_installed
        dependencies = list(dist.iter_dependencies())
      File "/usr/local/lib/python3.10/dist-packages/pip/_internal/metadata/pkg_resources.py", line 216, in iter_dependencies
        return self._dist.requires(extras)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 2821, in requires
        dm = self._dep_map
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3110, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3120, in _compute_dependencies
        reqs.extend(parse_requirements(req))
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 3173, in __init__
        super(Requirement, self).__init__(requirement_string)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/packaging/requirements.py", line 102, in __init__
        req = REQUIREMENT.parseString(requirement_string)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 1131, in parse_string
        loc, tokens = self._parse(instring, 0)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 3886, in parseImpl
        loc, exprtokens = e._parse(instring, loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 4114, in parseImpl
        return e._parse(
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 3886, in parseImpl
        loc, exprtokens = e._parse(instring, loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 4959, in parseImpl
        loc, tokens = self_expr._parse(instring, loc, doActions, callPreParse=False)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 3886, in parseImpl
        loc, exprtokens = e._parse(instring, loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 856, in _parseNoCache
        tokens = fn(instring, tokens_start, ret_tokens)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 291, in wrapper
        ret = func(*args[limit:])
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/packaging/requirements.py", line 71, in <lambda>
        lambda s, l, t: Marker(s[t._original_start : t._original_end])
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/packaging/markers.py", line 278, in __init__
        self._markers = _coerce_parse_result(MARKER.parseString(marker))
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 1131, in parse_string
        loc, tokens = self._parse(instring, 0)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 3886, in parseImpl
        loc, exprtokens = e._parse(instring, loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 5226, in parseImpl
        return super().parseImpl(instring, loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 4375, in parseImpl
        return self.expr._parse(instring, loc, doActions, callPreParse=False)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 3864, in parseImpl
        loc, resultlist = self.exprs[0]._parse(
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 4114, in parseImpl
        return e._parse(
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 4375, in parseImpl
        return self.expr._parse(instring, loc, doActions, callPreParse=False)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 3886, in parseImpl
        loc, exprtokens = e._parse(instring, loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 4114, in parseImpl
        return e._parse(
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 817, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 4114, in parseImpl
        return e._parse(
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 821, in _parseNoCache
        loc, tokens = self.parseImpl(instring, pre_loc, doActions)
      File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyparsing/core.py", line 2341, in parseImpl
        raise ParseException(instring, loc, self.errmsg, self)
    KeyboardInterrupt
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.10/logging/__init__.py", line 1732, in isEnabledFor
        return self._cache[level]
    KeyError: 50
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/bin/pip3", line 8, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/main.py", line 79, in main
        return command.main(cmd_args)
      File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 101, in main
        return self._main(args)
      File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
        return run(options, args)
      File "/usr/local/lib/python3.10/dist-packages/pip/_internal/cli/base_command.py", line 206, in exc_logging_wrapper
        logger.critical("Operation cancelled by user")
      File "/usr/lib/python3.10/logging/__init__.py", line 1523, in critical
        if self.isEnabledFor(CRITICAL):
      File "/usr/lib/python3.10/logging/__init__.py", line 1734, in isEnabledFor
        _acquireLock()
      File "/usr/lib/python3.10/logging/__init__.py", line 219, in _acquireLock
        def _acquireLock():
    KeyboardInterrupt
    ^C
    


```python
import cv2
import numpy as np
import matplotlib.pyplot as plt
```

## 1. GitHub 저장소를 이용해 이미지 Import 실습

### 1.1 GitHub 저장소에서 이미지 불러오기


```python
!wget https://raw.githubusercontent.com/BupyeongHealer/sample-image/7584aac88d1353fa35c3c9df67430056a804fce1/coin.jpg
```

    --2024-07-24 07:31:14--  https://raw.githubusercontent.com/BupyeongHealer/sample-image/7584aac88d1353fa35c3c9df67430056a804fce1/coin.jpg
    Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
    Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 62913 (61K) [image/jpeg]
    Saving to: ‘coin.jpg’
    
    coin.jpg              0%[                    ]       0  --.-KB/s               coin.jpg            100%[===================>]  61.44K  --.-KB/s    in 0.02s   
    
    2024-07-24 07:31:14 (2.81 MB/s) - ‘coin.jpg’ saved [62913/62913]
    
    


```python
img = cv2.imread('coin.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.subplot(121)
plt.imshow(img, cmap='gray')
plt.title('Original Image')
plt.xticks([]), plt.yticks([])
plt.show()
```


    
![png](240724_CVB%EA%B0%95%EC%9D%986_%EA%B3%A0%EC%A0%84%EC%BB%B4%ED%93%A8%ED%84%B0%EB%B9%84%EC%A0%84_%EC%8B%AC%ED%99%94%EC%98%88%EC%A0%9C%EC%8B%A4%EC%8A%B5_files/240724_CVB%EA%B0%95%EC%9D%986_%EA%B3%A0%EC%A0%84%EC%BB%B4%ED%93%A8%ED%84%B0%EB%B9%84%EC%A0%84_%EC%8B%AC%ED%99%94%EC%98%88%EC%A0%9C%EC%8B%A4%EC%8A%B5_8_0.png)
    


## 2. OpenCV Library를 이용한 Canny Edge Detection 실습

### 2.1 OpenCV Library를 활용하여 Canny Edge Detector 구현 및 입출력 비교하기


```python
edges = cv2.Canny(img, 350, 500) # 350: lower threshold / 500: upper threshold
```


```python
plt.subplot(121), plt.imshow(img)
plt.title('Original Image'), plt.xticks([]), plt.yticks([])
plt.subplot(122), plt.imshow(edges)
plt.title('Edge Image'), plt.xticks([]), plt.yticks([])

plt.show()
```


    
![png](240724_CVB%EA%B0%95%EC%9D%986_%EA%B3%A0%EC%A0%84%EC%BB%B4%ED%93%A8%ED%84%B0%EB%B9%84%EC%A0%84_%EC%8B%AC%ED%99%94%EC%98%88%EC%A0%9C%EC%8B%A4%EC%8A%B5_files/240724_CVB%EA%B0%95%EC%9D%986_%EA%B3%A0%EC%A0%84%EC%BB%B4%ED%93%A8%ED%84%B0%EB%B9%84%EC%A0%84_%EC%8B%AC%ED%99%94%EC%98%88%EC%A0%9C%EC%8B%A4%EC%8A%B5_12_0.png)
    


## 3. OpenCV Library를 이용한 Contour Detection 실습

### 3.1 OpenCV Library를 활용하여 Contour Detection 구현 및 입출력 비교하기


```python
# cv2.RETR_EXTERNAL: 최외곽의 컨투어(외부경계)만 검출하도록 하는 함수
# cv2.CHAIN_APPROX_SIMPLE: 컨투어를 단순화하여 저장할 방법. 불필요한 점들을 제거하고 꼭 필요한 점들만 남김
contours, _ = cv2.findContours(edges, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# 원본 이미지의 복사본을 생성해서 복사본의 경계선을 초록색으로 그림
image_copy = img.copy()
cv2.drawContours(image_copy, contours, -1, (0,255,0), 2) # -1: 모든 컨투어를 그리도록 지정 / 2: 컨투어 선의 두께

print(len(contours))
```

    983
    


```python
plt.subplot(121), plt.imshow(edges)
plt.title('Edge Image')
plt.xticks([]), plt.yticks([])

plt.subplot(122), plt.imshow(image_copy)
plt.title('Contour Image')
plt.xticks([]), plt.yticks([])

plt.show()
```


    
![png](240724_CVB%EA%B0%95%EC%9D%986_%EA%B3%A0%EC%A0%84%EC%BB%B4%ED%93%A8%ED%84%B0%EB%B9%84%EC%A0%84_%EC%8B%AC%ED%99%94%EC%98%88%EC%A0%9C%EC%8B%A4%EC%8A%B5_files/240724_CVB%EA%B0%95%EC%9D%986_%EA%B3%A0%EC%A0%84%EC%BB%B4%ED%93%A8%ED%84%B0%EB%B9%84%EC%A0%84_%EC%8B%AC%ED%99%94%EC%98%88%EC%A0%9C%EC%8B%A4%EC%8A%B5_16_0.png)
    


### 3.2 Dilation Kernel을 활용하여 Contour Detection 성능 개선하기


```python
# Dilation 연산에 사용할 커널 정의
kernel = np.ones((3,3), np.uint8)

# Dilation 연산 수행
dilate = cv2.dilate(edges, kernel, iterations=3)
```


```python
contours, _ = cv2.findContours(dilate, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

image_copy = img.copy()
cv2.drawContours(image_copy, contours, -1, (0,255,0), 2)

print(len(contours))
```

    7
    


```python
plt.subplot(121), plt.imshow(edges)
plt.title('Edge Image')
plt.xticks([]), plt.yticks([])

plt.subplot(122), plt.imshow(image_copy)
plt.title('Contour Image')
plt.xticks([]), plt.yticks([])
```




    (([], []), ([], []))




    
![png](240724_CVB%EA%B0%95%EC%9D%986_%EA%B3%A0%EC%A0%84%EC%BB%B4%ED%93%A8%ED%84%B0%EB%B9%84%EC%A0%84_%EC%8B%AC%ED%99%94%EC%98%88%EC%A0%9C%EC%8B%A4%EC%8A%B5_files/240724_CVB%EA%B0%95%EC%9D%986_%EA%B3%A0%EC%A0%84%EC%BB%B4%ED%93%A8%ED%84%B0%EB%B9%84%EC%A0%84_%EC%8B%AC%ED%99%94%EC%98%88%EC%A0%9C%EC%8B%A4%EC%8A%B5_20_1.png)
    

